import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_add_email_verification"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        # ── FHIRPatient ──────────────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRPatient",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mrn", models.CharField(db_index=True, max_length=50)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("middle_name", models.CharField(blank=True, default="", max_length=150)),
                ("birth_date", models.DateField()),
                ("gender", models.CharField(choices=[("male", "Male"), ("female", "Female"), ("other", "Other"), ("unknown", "Unknown")], default="unknown", max_length=10)),
                ("deceased", models.BooleanField(default=False)),
                ("deceased_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address_line1", models.CharField(blank=True, default="", max_length=255)),
                ("address_line2", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=50)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("country", models.CharField(default="US", max_length=50)),
                ("ssn_last4", models.CharField(blank=True, default="", max_length=4)),
                ("external_id", models.CharField(blank=True, default="", max_length=100)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("telecom", models.JSONField(blank=True, default=list)),
                ("communication", models.JSONField(blank=True, default=list)),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("primary_care_provider", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="primary_patients", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddIndex(model_name="fhirpatient", index=models.Index(fields=["tenant", "last_name", "first_name"], name="fhir_pt_ten_name_idx")),
        migrations.AddIndex(model_name="fhirpatient", index=models.Index(fields=["tenant", "mrn"], name="fhir_pt_ten_mrn_idx")),
        migrations.AddIndex(model_name="fhirpatient", index=models.Index(fields=["tenant", "birth_date"], name="fhir_pt_ten_dob_idx")),

        # ── FHIRObservation ──────────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRObservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("registered", "Registered"), ("preliminary", "Preliminary"), ("final", "Final"), ("amended", "Amended"), ("corrected", "Corrected"), ("cancelled", "Cancelled"), ("entered-in-error", "Entered in Error")], default="final", max_length=20)),
                ("code_system", models.CharField(default="http://loinc.org", max_length=100)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("display", models.CharField(max_length=255)),
                ("value_quantity", models.FloatField(blank=True, null=True)),
                ("value_unit", models.CharField(blank=True, default="", max_length=50)),
                ("value_string", models.CharField(blank=True, default="", max_length=500)),
                ("value_codeable_concept", models.JSONField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("reference_range_low", models.FloatField(blank=True, null=True)),
                ("reference_range_high", models.FloatField(blank=True, null=True)),
                ("interpretation", models.CharField(blank=True, default="", max_length=20)),
                ("effective_datetime", models.DateTimeField(db_index=True)),
                ("issued", models.DateTimeField(default=django.utils.timezone.now)),
                ("performer_id", models.UUIDField(blank=True, null=True)),
                ("components", models.JSONField(blank=True, default=list)),
                ("device_id", models.CharField(blank=True, default="", max_length=100)),
                ("device_type", models.CharField(blank=True, default="", max_length=50)),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-effective_datetime"]},
        ),
        migrations.AddIndex(model_name="fhirobservation", index=models.Index(fields=["patient", "code", "effective_datetime"], name="fhir_obs_pt_code_dt_idx")),
        migrations.AddIndex(model_name="fhirobservation", index=models.Index(fields=["tenant", "code", "effective_datetime"], name="fhir_obs_ten_code_dt_idx")),

        # ── FHIRCondition ────────────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRCondition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clinical_status", models.CharField(choices=[("active", "Active"), ("recurrence", "Recurrence"), ("relapse", "Relapse"), ("inactive", "Inactive"), ("remission", "Remission"), ("resolved", "Resolved")], default="active", max_length=20)),
                ("verification_status", models.CharField(choices=[("unconfirmed", "Unconfirmed"), ("provisional", "Provisional"), ("differential", "Differential"), ("confirmed", "Confirmed"), ("refuted", "Refuted")], default="confirmed", max_length=20)),
                ("code_system", models.CharField(default="http://hl7.org/fhir/sid/icd-10-cm", max_length=100)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("display", models.CharField(max_length=255)),
                ("snomed_code", models.CharField(blank=True, default="", max_length=20)),
                ("category", models.CharField(default="encounter-diagnosis", max_length=50)),
                ("severity", models.CharField(blank=True, default="", max_length=20)),
                ("onset_datetime", models.DateTimeField(blank=True, null=True)),
                ("onset_string", models.CharField(blank=True, default="", max_length=100)),
                ("abatement_datetime", models.DateTimeField(blank=True, null=True)),
                ("recorded_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("recorder_id", models.UUIDField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conditions", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-recorded_date"]},
        ),
        migrations.AddIndex(model_name="fhircondition", index=models.Index(fields=["patient", "code", "clinical_status"], name="fhir_cond_pt_code_cs_idx")),
        migrations.AddIndex(model_name="fhircondition", index=models.Index(fields=["tenant", "code"], name="fhir_cond_ten_code_idx")),

        # ── FHIRMedicationRequest ────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRMedicationRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("on-hold", "On Hold"), ("cancelled", "Cancelled"), ("completed", "Completed"), ("entered-in-error", "Entered in Error"), ("stopped", "Stopped"), ("draft", "Draft"), ("unknown", "Unknown")], db_index=True, default="active", max_length=25)),
                ("intent", models.CharField(choices=[("proposal", "Proposal"), ("plan", "Plan"), ("order", "Order"), ("original-order", "Original Order"), ("reflex-order", "Reflex Order"), ("filler-order", "Filler Order"), ("instance-order", "Instance Order"), ("option", "Option")], default="order", max_length=20)),
                ("medication_code", models.CharField(db_index=True, max_length=20)),
                ("medication_display", models.CharField(max_length=255)),
                ("medication_system", models.CharField(default="http://www.nlm.nih.gov/research/umls/rxnorm", max_length=100)),
                ("dosage_text", models.CharField(blank=True, default="", max_length=500)),
                ("dose_quantity", models.FloatField(blank=True, null=True)),
                ("dose_unit", models.CharField(blank=True, default="", max_length=50)),
                ("frequency", models.CharField(blank=True, default="", max_length=100)),
                ("route", models.CharField(blank=True, default="", max_length=100)),
                ("as_needed", models.BooleanField(default=False)),
                ("quantity_value", models.FloatField(blank=True, null=True)),
                ("days_supply", models.PositiveIntegerField(blank=True, null=True)),
                ("number_of_repeats_allowed", models.PositiveIntegerField(blank=True, null=True)),
                ("requester_id", models.UUIDField(blank=True, null=True)),
                ("authored_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("validity_period_start", models.DateTimeField(blank=True, null=True)),
                ("validity_period_end", models.DateTimeField(blank=True, null=True)),
                ("reason_code", models.CharField(blank=True, default="", max_length=20)),
                ("reason_display", models.CharField(blank=True, default="", max_length=255)),
                ("note", models.TextField(blank=True, default="")),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="medication_requests", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-authored_on"]},
        ),
        migrations.AddIndex(model_name="fhirmedicationrequest", index=models.Index(fields=["patient", "status", "authored_on"], name="fhir_med_pt_st_ao_idx")),
        migrations.AddIndex(model_name="fhirmedicationrequest", index=models.Index(fields=["tenant", "medication_code"], name="fhir_med_ten_mc_idx")),

        # ── FHIRAppointment ──────────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRAppointment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("proposed", "Proposed"), ("pending", "Pending"), ("booked", "Booked"), ("arrived", "Arrived"), ("fulfilled", "Fulfilled"), ("cancelled", "Cancelled"), ("noshow", "No Show"), ("entered-in-error", "Entered in Error"), ("checked-in", "Checked In"), ("waitlist", "Waitlist")], db_index=True, default="booked", max_length=20)),
                ("service_type", models.CharField(blank=True, default="", max_length=100)),
                ("specialty", models.CharField(blank=True, default="", max_length=100)),
                ("appointment_type", models.CharField(blank=True, default="", max_length=50)),
                ("reason_code", models.CharField(blank=True, default="", max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("start", models.DateTimeField(db_index=True)),
                ("end", models.DateTimeField()),
                ("minutes_duration", models.PositiveIntegerField(blank=True, null=True)),
                ("provider_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("is_telehealth", models.BooleanField(default=False)),
                ("telehealth_url", models.URLField(blank=True, default="")),
                ("comment", models.TextField(blank=True, default="")),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-start"]},
        ),
        migrations.AddIndex(model_name="fhirappointment", index=models.Index(fields=["tenant", "start", "status"], name="fhir_appt_ten_st_s_idx")),
        migrations.AddIndex(model_name="fhirappointment", index=models.Index(fields=["patient", "start"], name="fhir_appt_pt_start_idx")),

        # ── FHIRDiagnosticReport (M2M with FHIRObservation) ──────────────────
        migrations.CreateModel(
            name="FHIRDiagnosticReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("registered", "Registered"), ("partial", "Partial"), ("preliminary", "Preliminary"), ("final", "Final"), ("amended", "Amended"), ("corrected", "Corrected"), ("appended", "Appended"), ("cancelled", "Cancelled"), ("entered-in-error", "Entered in Error")], default="final", max_length=25)),
                ("category_code", models.CharField(blank=True, default="", max_length=20)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("display", models.CharField(max_length=255)),
                ("effective_datetime", models.DateTimeField(db_index=True)),
                ("issued", models.DateTimeField(default=django.utils.timezone.now)),
                ("conclusion", models.TextField(blank=True, default="")),
                ("conclusion_code", models.CharField(blank=True, default="", max_length=20)),
                ("performer_id", models.UUIDField(blank=True, null=True)),
                ("presented_form", models.JSONField(blank=True, default=list)),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="diagnostic_reports", to="fhir.fhirpatient")),
                ("results", models.ManyToManyField(blank=True, related_name="diagnostic_reports", to="fhir.fhirobservation")),
            ],
            options={"ordering": ["-effective_datetime"]},
        ),

        # ── FHIRCarePlan (M2M with FHIRCondition) ───────────────────────────
        migrations.CreateModel(
            name="FHIRCarePlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("on-hold", "On Hold"), ("revoked", "Revoked"), ("completed", "Completed"), ("entered-in-error", "Entered in Error"), ("unknown", "Unknown")], db_index=True, default="active", max_length=20)),
                ("intent", models.CharField(choices=[("proposal", "Proposal"), ("plan", "Plan"), ("order", "Order"), ("option", "Option")], default="plan", max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(default="assess-plan", max_length=50)),
                ("goals", models.JSONField(blank=True, default=list)),
                ("activities", models.JSONField(blank=True, default=list)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("author_id", models.UUIDField(blank=True, null=True)),
                ("ai_generated", models.BooleanField(default=False)),
                ("ai_model_used", models.CharField(blank=True, default="", max_length=100)),
                ("note", models.TextField(blank=True, default="")),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="care_plans", to="fhir.fhirpatient")),
                ("addresses", models.ManyToManyField(blank=True, related_name="care_plans", to="fhir.fhircondition")),
            ],
            options={"ordering": ["-created"]},
        ),

        # ── FHIRAllergyIntolerance ───────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRAllergyIntolerance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clinical_status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("resolved", "Resolved")], default="active", max_length=20)),
                ("verification_status", models.CharField(choices=[("unconfirmed", "Unconfirmed"), ("confirmed", "Confirmed"), ("refuted", "Refuted"), ("entered-in-error", "Entered in Error")], default="confirmed", max_length=20)),
                ("category", models.CharField(choices=[("food", "Food"), ("medication", "Medication"), ("environment", "Environment"), ("biologic", "Biologic")], default="medication", max_length=20)),
                ("criticality", models.CharField(choices=[("low", "Low"), ("high", "High"), ("unable-to-assess", "Unable to Assess")], default="low", max_length=20)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("display", models.CharField(max_length=255)),
                ("code_system", models.CharField(blank=True, default="", max_length=100)),
                ("reactions", models.JSONField(blank=True, default=list)),
                ("onset_datetime", models.DateTimeField(blank=True, null=True)),
                ("recorded_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("recorder_id", models.UUIDField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allergies", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-recorded_date"]},
        ),

        # ── FHIREncounter ────────────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIREncounter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("arrived", "Arrived"), ("triaged", "Triaged"), ("in-progress", "In Progress"), ("on-leave", "On Leave"), ("finished", "Finished"), ("cancelled", "Cancelled"), ("entered-in-error", "Entered in Error"), ("unknown", "Unknown")], db_index=True, default="finished", max_length=20)),
                ("encounter_class", models.CharField(default="AMB", max_length=50)),
                ("type_code", models.CharField(blank=True, default="", max_length=20)),
                ("type_display", models.CharField(blank=True, default="", max_length=255)),
                ("service_type", models.CharField(blank=True, default="", max_length=100)),
                ("reason_code", models.CharField(blank=True, default="", max_length=20)),
                ("reason_display", models.CharField(blank=True, default="", max_length=255)),
                ("period_start", models.DateTimeField(db_index=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("length_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("participants", models.JSONField(blank=True, default=list)),
                ("location", models.JSONField(blank=True, default=list)),
                ("discharge_disposition", models.CharField(blank=True, default="", max_length=50)),
                ("hospitalization", models.JSONField(blank=True, null=True)),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fhir_encounters", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-period_start"]},
        ),

        # ── FHIRProcedure ────────────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRProcedure",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("preparation", "Preparation"), ("in-progress", "In Progress"), ("not-done", "Not Done"), ("on-hold", "On Hold"), ("stopped", "Stopped"), ("completed", "Completed"), ("entered-in-error", "Entered in Error"), ("unknown", "Unknown")], default="completed", max_length=25)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("display", models.CharField(max_length=255)),
                ("code_system", models.CharField(blank=True, default="", max_length=100)),
                ("category", models.CharField(blank=True, default="", max_length=50)),
                ("performed_datetime", models.DateTimeField(db_index=True)),
                ("performer_id", models.UUIDField(blank=True, null=True)),
                ("body_site", models.JSONField(blank=True, default=list)),
                ("outcome_code", models.CharField(blank=True, default="", max_length=20)),
                ("outcome_display", models.CharField(blank=True, default="", max_length=255)),
                ("note", models.TextField(blank=True, default="")),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="procedures", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-performed_datetime"]},
        ),

        # ── FHIRImmunization ─────────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRImmunization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("completed", "Completed"), ("entered-in-error", "Entered in Error"), ("not-done", "Not Done")], default="completed", max_length=20)),
                ("vaccine_code", models.CharField(db_index=True, max_length=20)),
                ("vaccine_display", models.CharField(max_length=255)),
                ("occurrence_datetime", models.DateTimeField(db_index=True)),
                ("lot_number", models.CharField(blank=True, default="", max_length=50)),
                ("manufacturer", models.CharField(blank=True, default="", max_length=100)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("dose_quantity_value", models.FloatField(blank=True, null=True)),
                ("dose_quantity_unit", models.CharField(blank=True, default="", max_length=50)),
                ("site", models.CharField(blank=True, default="", max_length=100)),
                ("route", models.CharField(blank=True, default="", max_length=100)),
                ("performer_id", models.UUIDField(blank=True, null=True)),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="immunizations", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-occurrence_datetime"]},
        ),

        # ── FHIRDocumentReference ────────────────────────────────────────────
        migrations.CreateModel(
            name="FHIRDocumentReference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fhir_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("meta_version_id", models.CharField(default="1", max_length=20)),
                ("meta_last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta_profile", django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ("raw_resource", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("current", "Current"), ("superseded", "Superseded"), ("entered-in-error", "Entered in Error")], default="current", max_length=20)),
                ("doc_status", models.CharField(choices=[("preliminary", "Preliminary"), ("final", "Final"), ("amended", "Amended")], default="final", max_length=20)),
                ("type_code", models.CharField(db_index=True, max_length=20)),
                ("type_display", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, default="", max_length=50)),
                ("content_url", models.URLField(blank=True, default="")),
                ("content_mime_type", models.CharField(default="text/plain", max_length=100)),
                ("content_data", models.TextField(blank=True, default="")),
                ("content_title", models.CharField(blank=True, default="", max_length=255)),
                ("date", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("author_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("embedding_id", models.CharField(blank=True, default="", max_length=100)),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="document_references", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-date"]},
        ),

        # ── AgentActionLog ───────────────────────────────────────────────────
        migrations.CreateModel(
            name="AgentActionLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("agent_type", models.CharField(choices=[("triage", "Triage Agent"), ("medication", "Medication Safety Agent"), ("care_plan", "Care Plan Agent"), ("diagnostic", "Diagnostic Agent"), ("research", "Research Agent"), ("patient_engagement", "Patient Engagement Agent"), ("population_health", "Population Health Agent"), ("orchestrator", "Orchestrator Agent")], db_index=True, max_length=30)),
                ("action_type", models.CharField(choices=[("alert_generated", "Alert Generated"), ("recommendation", "Recommendation Made"), ("order_suggested", "Order Suggested"), ("care_plan_updated", "Care Plan Updated"), ("risk_calculated", "Risk Score Calculated"), ("literature_searched", "Literature Searched"), ("message_sent", "Patient Message Sent"), ("tool_called", "Tool Called")], db_index=True, max_length=30)),
                ("action_details", models.JSONField(default=dict)),
                ("input_context", models.JSONField(default=dict)),
                ("output", models.JSONField(default=dict)),
                ("model_used", models.CharField(blank=True, default="", max_length=100)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("tokens_used", models.PositiveIntegerField(blank=True, null=True)),
                ("langfuse_trace_id", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reviewed_by_id", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("was_accepted", models.BooleanField(blank=True, null=True)),
                ("tenant", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.organization")),
                ("patient", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="agent_actions", to="fhir.fhirpatient")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="agentactionlog", index=models.Index(fields=["tenant", "created_at"], name="fhir_aal_ten_cat_idx")),
        migrations.AddIndex(model_name="agentactionlog", index=models.Index(fields=["patient", "agent_type", "created_at"], name="fhir_aal_pt_at_cat_idx")),
    ]
