"""
Analytics models — population health, risk scores, and KPIs.
"""

import uuid

from django.db import models
from django.utils import timezone


class PopulationCohort(models.Model):
    """
    Defines a population health cohort for analytics.
    E.g., "All diabetic patients with A1C > 9" or "CHF patients admitted in last 90 days".
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tenant = models.ForeignKey("tenants.Organization", on_delete=models.CASCADE, db_index=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    condition_filter = models.JSONField(
        default=dict,
        help_text="""
        {
          "icd10_codes": ["E11", "I50"],
          "age_min": 18,
          "age_max": 80,
          "risk_level": ["high", "critical"],
          "has_active_condition": true
        }
        """,
    )
    created_by = models.ForeignKey(
        "accounts.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="created_cohorts",
    )
    patient_count = models.PositiveIntegerField(default=0)
    last_refreshed = models.DateTimeField(null=True, blank=True)
    refresh_frequency_hours = models.PositiveIntegerField(default=24)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["tenant", "is_active"]),
        ]

    def __str__(self):
        return f"Cohort: {self.name} ({self.patient_count} patients)"

    def is_stale(self) -> bool:
        if not self.last_refreshed:
            return True
        from datetime import timedelta
        return timezone.now() > self.last_refreshed + timedelta(hours=self.refresh_frequency_hours)


class RiskScore(models.Model):
    """
    ML-computed risk scores for individual patients.
    Generated by XGBoost and multi-modal models.
    """

    class ScoreType(models.TextChoices):
        HOSPITALIZATION_7D = "7_day_hospitalization", "7-Day Hospitalization Risk"
        MORTALITY_30D = "30_day_mortality", "30-Day Mortality Risk"
        READMISSION_30D = "30_day_readmission", "30-Day Readmission Risk"
        ED_VISIT_30D = "30_day_ed_visit", "30-Day ED Visit Risk"
        MEDICATION_NONADHERENCE = "medication_nonadherence", "Medication Non-Adherence Risk"
        GLUCOSE_CONTROL = "glucose_control", "Poor Glucose Control Risk"
        FALLS = "falls_risk", "Falls Risk"
        SEPSIS = "sepsis_risk", "Sepsis Risk"

    class RiskLevel(models.TextChoices):
        LOW = "low", "Low (<30%)"
        MEDIUM = "medium", "Medium (30-60%)"
        HIGH = "high", "High (60-80%)"
        CRITICAL = "critical", "Critical (>80%)"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    patient = models.ForeignKey(
        "fhir.FHIRPatient",
        on_delete=models.CASCADE,
        related_name="analytics_risk_scores",
        db_index=True,
    )
    tenant = models.ForeignKey("tenants.Organization", on_delete=models.CASCADE, db_index=True)

    score_type = models.CharField(max_length=30, choices=ScoreType.choices, db_index=True)
    score = models.FloatField()  # 0.0 - 1.0
    risk_level = models.CharField(max_length=10, choices=RiskLevel.choices, db_index=True)

    # Feature importance from XGBoost
    features = models.JSONField(
        default=dict,
        blank=True,
        help_text='{"a1c_value": 0.32, "bp_systolic": 0.18, "age": 0.15, "comorbidities": 0.12}',
    )

    model_version = models.CharField(max_length=50, default="xgboost_v1")
    calculated_at = models.DateTimeField(auto_now_add=True, db_index=True)
    valid_until = models.DateTimeField(db_index=True)

    class Meta:
        ordering = ["-calculated_at"]
        indexes = [
            models.Index(fields=["patient", "score_type", "calculated_at"]),
            models.Index(fields=["tenant", "risk_level", "valid_until"]),
        ]

    def __str__(self):
        return f"Risk {self.score_type}: {self.score:.2%} ({self.risk_level}) — {self.patient}"

    @classmethod
    def categorize_score(cls, score: float) -> str:
        if score < 0.30:
            return cls.RiskLevel.LOW
        elif score < 0.60:
            return cls.RiskLevel.MEDIUM
        elif score < 0.80:
            return cls.RiskLevel.HIGH
        else:
            return cls.RiskLevel.CRITICAL

    def save(self, *args, **kwargs):
        self.risk_level = self.categorize_score(self.score)
        if not self.valid_until:
            from datetime import timedelta
            self.valid_until = timezone.now() + timedelta(hours=24)
        super().save(*args, **kwargs)


class ClinicalKPI(models.Model):
    """
    Tenant-level clinical quality KPIs.
    Tracks population health metrics over time.
    """

    class MetricName(models.TextChoices):
        AVG_A1C = "avg_a1c", "Average A1C"
        PCT_A1C_CONTROLLED = "pct_a1c_controlled", "% Patients A1C < 8.0"
        PCT_BP_CONTROLLED = "pct_bp_controlled", "% Patients BP Controlled"
        READMISSION_RATE_30D = "readmission_rate_30d", "30-Day Readmission Rate"
        ED_VISIT_RATE = "ed_visit_rate", "ED Visit Rate per 1000"
        CARE_GAP_CLOSURE_RATE = "care_gap_closure_rate", "Care Gap Closure Rate"
        MEDICATION_ADHERENCE_RATE = "medication_adherence_rate", "Medication Adherence Rate"
        PATIENT_SATISFACTION = "patient_satisfaction", "Patient Satisfaction Score"
        AVG_ENGAGEMENT_SCORE = "avg_engagement_score", "Average Patient Engagement Score"
        ALERT_RESPONSE_TIME_MINUTES = "alert_response_time_min", "Average Alert Response Time (minutes)"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tenant = models.ForeignKey("tenants.Organization", on_delete=models.CASCADE, db_index=True)
    metric_name = models.CharField(max_length=50, choices=MetricName.choices, db_index=True)
    metric_value = models.FloatField()
    metric_date = models.DateField(db_index=True)
    unit = models.CharField(max_length=20, blank=True, default="")
    metadata = models.JSONField(default=dict, blank=True)
    calculated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-metric_date"]
        unique_together = [("tenant", "metric_name", "metric_date")]
        indexes = [
            models.Index(fields=["tenant", "metric_name", "metric_date"]),
        ]

    def __str__(self):
        return f"KPI {self.metric_name}: {self.metric_value} ({self.metric_date})"
