import { AgentCard } from "./types";

// Complete registry of all 25 InHealth agents across 6 tiers
export const AGENT_REGISTRY: AgentCard[] = [
  // ─── TIER 1: Monitoring Agents ─────────────────────────────────────────────
  {
    id: 1,
    name: "Glucose Monitoring Agent",
    type: "monitoring",
    tier: 1,
    description:
      "Continuously monitors blood glucose readings from CGM devices and FHIR observations. Detects hypoglycemia, hyperglycemia, and glycemic variability patterns.",
    capabilities: [
      "realtime_glucose_monitoring",
      "hypoglycemia_detection",
      "hyperglycemia_detection",
      "glycemic_variability_analysis",
      "hba1c_trending",
      "cgm_data_ingestion",
    ],
    subscribed_channels: ["agent.monitoring"],
    publishes_to: ["agent.diagnostic", "agent.risk", "agent.broadcast"],
    endpoint: "http://glucose-monitoring-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 2,
    name: "Cardiac Monitoring Agent",
    type: "monitoring",
    tier: 1,
    description:
      "Monitors cardiac vitals including ECG, heart rate, blood pressure, and arrhythmia patterns. Integrates with wearable devices and hospital monitoring systems.",
    capabilities: [
      "ecg_analysis",
      "arrhythmia_detection",
      "blood_pressure_monitoring",
      "heart_rate_variability",
      "afib_detection",
      "cardiac_biomarker_monitoring",
    ],
    subscribed_channels: ["agent.monitoring"],
    publishes_to: ["agent.diagnostic", "agent.risk", "agent.broadcast"],
    endpoint: "http://cardiac-monitoring-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 3,
    name: "Medication Adherence Agent",
    type: "monitoring",
    tier: 1,
    description:
      "Tracks patient medication adherence through EHR data, smart pill dispensers, and pharmacy refill records. Identifies adherence gaps and patterns.",
    capabilities: [
      "adherence_tracking",
      "refill_monitoring",
      "smart_dispenser_integration",
      "adherence_scoring",
      "missed_dose_detection",
      "adherence_barrier_identification",
    ],
    subscribed_channels: ["agent.monitoring"],
    publishes_to: ["agent.intervention", "agent.risk", "agent.broadcast"],
    endpoint: "http://medication-adherence-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 4,
    name: "Vital Signs Agent",
    type: "monitoring",
    tier: 1,
    description:
      "Monitors comprehensive vital signs including SpO2, respiratory rate, temperature, and weight trends. Integrates with IoT medical devices and manual entry.",
    capabilities: [
      "vitals_aggregation",
      "spo2_monitoring",
      "respiratory_monitoring",
      "temperature_trending",
      "weight_tracking",
      "bmi_calculation",
      "vital_trend_analysis",
    ],
    subscribed_channels: ["agent.monitoring"],
    publishes_to: ["agent.diagnostic", "agent.risk", "agent.broadcast"],
    endpoint: "http://vital-signs-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 5,
    name: "Lab Results Agent",
    type: "monitoring",
    tier: 1,
    description:
      "Monitors incoming laboratory results from HL7 interfaces and FHIR DiagnosticReports. Flags critical values and tracks longitudinal trends for key biomarkers.",
    capabilities: [
      "lab_result_ingestion",
      "critical_value_alerting",
      "trend_analysis",
      "reference_range_evaluation",
      "longitudinal_tracking",
      "hl7_integration",
    ],
    subscribed_channels: ["agent.monitoring"],
    publishes_to: ["agent.diagnostic", "agent.risk", "agent.broadcast"],
    endpoint: "http://lab-results-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },

  // ─── TIER 2: Diagnostic Agents ────────────────────────────────────────────
  {
    id: 6,
    name: "Pattern Recognition Agent",
    type: "diagnostic",
    tier: 2,
    description:
      "Identifies complex clinical patterns across multiple data streams using time-series analysis and ML models. Detects early warning signs of clinical deterioration.",
    capabilities: [
      "multivariate_pattern_detection",
      "time_series_analysis",
      "anomaly_detection",
      "clinical_deterioration_scoring",
      "early_warning_system",
      "sepsis_prediction",
    ],
    subscribed_channels: ["agent.diagnostic"],
    publishes_to: ["agent.risk", "agent.broadcast"],
    endpoint: "http://pattern-recognition-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 7,
    name: "Drug Interaction Agent",
    type: "diagnostic",
    tier: 2,
    description:
      "Analyzes medication combinations for potentially dangerous interactions using Neo4j graph traversal of pharmacological knowledge graphs. Evaluates contraindications.",
    capabilities: [
      "drug_interaction_checking",
      "contraindication_analysis",
      "polypharmacy_review",
      "allergy_cross_reactivity",
      "dose_adjustment_recommendations",
      "neo4j_graph_traversal",
    ],
    subscribed_channels: ["agent.diagnostic"],
    publishes_to: ["agent.intervention", "agent.risk", "agent.broadcast"],
    endpoint: "http://drug-interaction-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 8,
    name: "Comorbidity Analysis Agent",
    type: "diagnostic",
    tier: 2,
    description:
      "Analyzes complex comorbidity interactions and disease progression patterns using clinical knowledge graphs and evidence-based guidelines.",
    capabilities: [
      "comorbidity_mapping",
      "disease_interaction_analysis",
      "charlson_index_calculation",
      "progression_prediction",
      "guideline_based_assessment",
      "knowledge_graph_reasoning",
    ],
    subscribed_channels: ["agent.diagnostic"],
    publishes_to: ["agent.risk", "agent.broadcast"],
    endpoint: "http://comorbidity-analysis-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 9,
    name: "Symptom Assessment Agent",
    type: "diagnostic",
    tier: 2,
    description:
      "Processes patient-reported symptoms through NLP and semantic matching to identify clinical presentations and recommend diagnostic workup pathways.",
    capabilities: [
      "nlp_symptom_extraction",
      "differential_diagnosis_support",
      "symptom_severity_scoring",
      "symptom_progression_tracking",
      "semantic_clinical_matching",
      "triage_scoring",
    ],
    subscribed_channels: ["agent.diagnostic"],
    publishes_to: ["agent.risk", "agent.intervention", "agent.broadcast"],
    endpoint: "http://symptom-assessment-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 10,
    name: "Imaging Analysis Agent",
    type: "diagnostic",
    tier: 2,
    description:
      "Processes radiology and pathology report findings from FHIR DiagnosticReports. Extracts key findings and flags abnormalities requiring clinical attention.",
    capabilities: [
      "radiology_report_analysis",
      "pathology_report_processing",
      "finding_extraction",
      "abnormality_flagging",
      "follow_up_recommendation",
      "dicom_metadata_processing",
    ],
    subscribed_channels: ["agent.diagnostic"],
    publishes_to: ["agent.risk", "agent.broadcast"],
    endpoint: "http://imaging-analysis-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },

  // ─── TIER 3: Risk Assessment Agents ──────────────────────────────────────
  {
    id: 11,
    name: "Diabetes Risk Agent",
    type: "risk",
    tier: 3,
    description:
      "Calculates comprehensive diabetes complication risk scores (retinopathy, nephropathy, neuropathy, cardiovascular) using validated ML models trained on longitudinal data.",
    capabilities: [
      "diabetes_complication_risk",
      "retinopathy_risk_scoring",
      "nephropathy_progression",
      "cardiovascular_risk_calculation",
      "hypoglycemia_risk_assessment",
      "hba1c_trajectory_modeling",
    ],
    subscribed_channels: ["agent.risk"],
    publishes_to: ["agent.intervention", "agent.broadcast"],
    endpoint: "http://diabetes-risk-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 12,
    name: "Cardiovascular Risk Agent",
    type: "risk",
    tier: 3,
    description:
      "Computes ASCVD, HEART, GRACE, and custom cardiovascular risk scores. Integrates Framingham risk factors with real-time vitals and biomarkers.",
    capabilities: [
      "ascvd_risk_calculation",
      "heart_score",
      "grace_score",
      "framingham_risk",
      "afib_stroke_risk",
      "cardiac_event_prediction",
    ],
    subscribed_channels: ["agent.risk"],
    publishes_to: ["agent.intervention", "agent.broadcast"],
    endpoint: "http://cardiovascular-risk-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 13,
    name: "Readmission Risk Agent",
    type: "risk",
    tier: 3,
    description:
      "Predicts 30-day hospital readmission risk using LACE+ and custom ensemble models. Identifies patients needing intensive post-discharge follow-up.",
    capabilities: [
      "readmission_prediction",
      "lace_plus_scoring",
      "discharge_risk_assessment",
      "post_acute_care_planning",
      "transitional_care_risk",
      "social_determinants_integration",
    ],
    subscribed_channels: ["agent.risk"],
    publishes_to: ["agent.intervention", "agent.broadcast"],
    endpoint: "http://readmission-risk-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 14,
    name: "Mental Health Risk Agent",
    type: "risk",
    tier: 3,
    description:
      "Assesses depression, anxiety, and suicide risk using validated screening tools (PHQ-9, GAD-7) and NLP analysis of clinical notes.",
    capabilities: [
      "depression_screening",
      "anxiety_assessment",
      "suicide_risk_evaluation",
      "phq9_scoring",
      "gad7_scoring",
      "clinical_note_nlp",
      "behavioral_health_risk",
    ],
    subscribed_channels: ["agent.risk"],
    publishes_to: ["agent.intervention", "agent.broadcast"],
    endpoint: "http://mental-health-risk-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 15,
    name: "Kidney Disease Risk Agent",
    type: "risk",
    tier: 3,
    description:
      "Monitors CKD progression using eGFR trajectories, proteinuria levels, and comorbidity interactions. Predicts ESRD risk and identifies nephrology referral triggers.",
    capabilities: [
      "ckd_staging",
      "egfr_trajectory_analysis",
      "esrd_risk_prediction",
      "proteinuria_monitoring",
      "nephrology_referral_triggers",
      "aki_detection",
    ],
    subscribed_channels: ["agent.risk"],
    publishes_to: ["agent.intervention", "agent.broadcast"],
    endpoint: "http://kidney-disease-risk-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 16,
    name: "Fall Risk Agent",
    type: "risk",
    tier: 3,
    description:
      "Assesses patient fall risk using Morse Fall Scale, medication analysis, gait assessments, and environmental factors. Coordinates preventive interventions.",
    capabilities: [
      "morse_fall_scale",
      "medication_fall_risk",
      "gait_assessment",
      "orthostatic_hypotension_risk",
      "cognitive_impairment_assessment",
      "environmental_risk_factors",
    ],
    subscribed_channels: ["agent.risk"],
    publishes_to: ["agent.intervention", "agent.broadcast"],
    endpoint: "http://fall-risk-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },

  // ─── TIER 4: Intervention Agents ─────────────────────────────────────────
  {
    id: 17,
    name: "Prescription Agent",
    type: "intervention",
    tier: 4,
    description:
      "Generates evidence-based medication recommendations, dose adjustments, and formulary alternatives. Performs pre-prescription safety checks against interactions and contraindications.",
    capabilities: [
      "medication_recommendations",
      "dose_calculation",
      "formulary_management",
      "prescription_safety_check",
      "generic_substitution",
      "therapeutic_substitution",
      "prior_auth_support",
    ],
    subscribed_channels: ["agent.intervention"],
    publishes_to: ["agent.action", "agent.broadcast"],
    endpoint: "http://prescription-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 18,
    name: "Triage Agent",
    type: "intervention",
    tier: 4,
    description:
      "Determines appropriate care setting and urgency level for patient conditions. Routes patients to ED, urgent care, telehealth, or scheduled visits based on clinical acuity.",
    capabilities: [
      "acuity_scoring",
      "care_setting_determination",
      "esi_scoring",
      "telehealth_eligibility",
      "emergency_escalation",
      "care_routing",
    ],
    subscribed_channels: ["agent.intervention"],
    publishes_to: ["agent.action", "agent.broadcast"],
    endpoint: "http://triage-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 19,
    name: "Care Plan Agent",
    type: "intervention",
    tier: 4,
    description:
      "Generates and updates personalized care plans based on clinical guidelines, patient preferences, and risk profiles. Coordinates care team activities.",
    capabilities: [
      "care_plan_generation",
      "goal_setting",
      "care_team_coordination",
      "guideline_based_planning",
      "patient_preference_integration",
      "care_gap_identification",
      "fhir_care_plan_management",
    ],
    subscribed_channels: ["agent.intervention"],
    publishes_to: ["agent.action", "agent.broadcast"],
    endpoint: "http://care-plan-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 20,
    name: "Patient Education Agent",
    type: "intervention",
    tier: 4,
    description:
      "Delivers personalized health education content based on patient conditions, literacy level, and language preference. Tracks engagement and knowledge assessment.",
    capabilities: [
      "personalized_content_delivery",
      "health_literacy_adaptation",
      "multilingual_education",
      "engagement_tracking",
      "teach_back_assessment",
      "video_and_text_content",
    ],
    subscribed_channels: ["agent.intervention"],
    publishes_to: ["agent.action", "agent.broadcast"],
    endpoint: "http://patient-education-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },

  // ─── TIER 5: Action Agents ────────────────────────────────────────────────
  {
    id: 21,
    name: "Notification Agent",
    type: "action",
    tier: 5,
    description:
      "Sends multi-channel notifications to patients, providers, and care teams via SMS, email, push notifications, and in-app messages. Manages escalation workflows.",
    capabilities: [
      "sms_notifications",
      "email_alerts",
      "push_notifications",
      "in_app_messaging",
      "escalation_workflows",
      "delivery_tracking",
      "preference_management",
    ],
    subscribed_channels: ["agent.action"],
    publishes_to: ["agent.broadcast"],
    endpoint: "http://notification-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 22,
    name: "Scheduling Agent",
    type: "action",
    tier: 5,
    description:
      "Manages appointment scheduling, provider matching, and care gap closure. Integrates with EHR scheduling systems and handles complex multi-specialty coordination.",
    capabilities: [
      "appointment_booking",
      "provider_matching",
      "care_gap_scheduling",
      "specialist_referral",
      "telehealth_scheduling",
      "reminder_management",
      "calendar_integration",
    ],
    subscribed_channels: ["agent.action"],
    publishes_to: ["agent.broadcast"],
    endpoint: "http://scheduling-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 23,
    name: "EHR Integration Agent",
    type: "action",
    tier: 5,
    description:
      "Writes AI-generated insights, care plan updates, and clinical documentation back to the EHR as structured FHIR resources. Manages SMART on FHIR authorizations.",
    capabilities: [
      "fhir_resource_creation",
      "clinical_note_generation",
      "care_plan_updates",
      "order_entry_support",
      "smart_on_fhir",
      "hl7_messaging",
      "cds_hooks_integration",
    ],
    subscribed_channels: ["agent.action"],
    publishes_to: ["agent.broadcast"],
    endpoint: "http://ehr-integration-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 24,
    name: "Emergency Response Agent",
    type: "action",
    tier: 5,
    description:
      "Coordinates emergency responses including 911 dispatch support, hospital diversion recommendations, and family notification for critical clinical events.",
    capabilities: [
      "emergency_escalation",
      "911_integration",
      "hospital_diversion",
      "family_notification",
      "care_team_emergency_alert",
      "geolocation_services",
      "crisis_protocol_execution",
    ],
    subscribed_channels: ["agent.action", "agent.broadcast"],
    publishes_to: ["agent.broadcast"],
    endpoint: "http://emergency-response-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 25,
    name: "Billing & Authorization Agent",
    type: "action",
    tier: 5,
    description:
      "Handles prior authorization requests, insurance eligibility verification, and care coordination billing documentation. Reduces administrative burden on care teams.",
    capabilities: [
      "prior_authorization",
      "eligibility_verification",
      "billing_documentation",
      "icd_code_suggestion",
      "cpt_coding_support",
      "claim_submission",
      "revenue_cycle_integration",
    ],
    subscribed_channels: ["agent.action"],
    publishes_to: ["agent.broadcast"],
    endpoint: "http://billing-auth-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },

  // ─── TIER 6: Research System Agents ──────────────────────────────────────
  {
    id: 26,
    name: "Literature Search Agent",
    type: "research",
    tier: 6,
    description:
      "Performs semantic search across PubMed, clinical trial registries, and internal knowledge bases to surface relevant evidence for clinical decisions.",
    capabilities: [
      "pubmed_search",
      "clinical_trial_search",
      "semantic_literature_search",
      "evidence_grading",
      "citation_management",
      "guideline_retrieval",
    ],
    subscribed_channels: ["agent.broadcast"],
    publishes_to: ["agent.diagnostic", "agent.risk"],
    endpoint: "http://literature-search-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 27,
    name: "Cohort Analysis Agent",
    type: "research",
    tier: 6,
    description:
      "Identifies similar patient cohorts for benchmarking, quality improvement, and outcome analysis. Supports population health management programs.",
    capabilities: [
      "cohort_identification",
      "patient_similarity_matching",
      "outcome_benchmarking",
      "quality_measure_reporting",
      "population_stratification",
      "nlp_phenotyping",
    ],
    subscribed_channels: ["agent.broadcast"],
    publishes_to: ["agent.risk"],
    endpoint: "http://cohort-analysis-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
  {
    id: 28,
    name: "Clinical Trial Matching Agent",
    type: "research",
    tier: 6,
    description:
      "Matches patients to relevant clinical trials based on eligibility criteria, condition profiles, and geographic proximity. Automates pre-screening workflows.",
    capabilities: [
      "trial_eligibility_matching",
      "inclusion_exclusion_screening",
      "geographic_proximity_matching",
      "enrollment_coordination",
      "ctgov_integration",
      "consent_workflow_support",
    ],
    subscribed_channels: ["agent.broadcast"],
    publishes_to: ["agent.intervention"],
    endpoint: "http://clinical-trial-matching-agent:8080",
    status: "active",
    last_heartbeat: new Date().toISOString(),
    version: "1.0.0",
  },
];

export function getAgentById(id: number): AgentCard | undefined {
  return AGENT_REGISTRY.find((a) => a.id === id);
}

export function getAgentsByType(type: AgentCard["type"]): AgentCard[] {
  return AGENT_REGISTRY.filter((a) => a.type === type);
}

export function getAgentsByTier(tier: number): AgentCard[] {
  return AGENT_REGISTRY.filter((a) => a.tier === tier);
}

export function getAgentsSubscribedToChannel(channel: string): AgentCard[] {
  return AGENT_REGISTRY.filter((a) => a.subscribed_channels.includes(channel));
}

export function getAgentsByCapability(capability: string): AgentCard[] {
  return AGENT_REGISTRY.filter((a) => a.capabilities.includes(capability));
}
