#!/bin/bash
# ============================================================
# InHealth Chronic Care - Setup Script
# Initializes the development environment
# ============================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo -e "${BLUE}"
echo "============================================================"
echo "  InHealth Chronic Care - Environment Setup"
echo "============================================================"
echo -e "${NC}"

# ============================================================
# Check requirements
# ============================================================
echo -e "${YELLOW}Checking requirements...${NC}"

# Check Docker
if ! command -v docker &> /dev/null; then
    echo -e "${RED}ERROR: Docker is not installed. Please install Docker >= 24.0${NC}"
    echo "  Installation: https://docs.docker.com/get-docker/"
    exit 1
fi

DOCKER_VERSION=$(docker --version | grep -oP '\d+\.\d+\.\d+' | head -1)
DOCKER_MAJOR=$(echo "$DOCKER_VERSION" | cut -d. -f1)
if [ "$DOCKER_MAJOR" -lt 24 ]; then
    echo -e "${YELLOW}WARNING: Docker version $DOCKER_VERSION detected. Version >= 24.0 recommended.${NC}"
fi
echo -e "  ${GREEN}Docker: $DOCKER_VERSION${NC}"

# Check Docker Compose
if ! command -v docker &> /dev/null || ! docker compose version &> /dev/null 2>&1; then
    # Try docker-compose fallback
    if ! command -v docker-compose &> /dev/null; then
        echo -e "${RED}ERROR: Docker Compose is not available. Please install Docker Compose >= 2.20${NC}"
        echo "  Installation: https://docs.docker.com/compose/install/"
        exit 1
    fi
    COMPOSE_CMD="docker-compose"
    COMPOSE_VERSION=$(docker-compose --version | grep -oP '\d+\.\d+\.\d+' | head -1)
else
    COMPOSE_CMD="docker compose"
    COMPOSE_VERSION=$(docker compose version | grep -oP '\d+\.\d+\.\d+' | head -1)
fi
echo -e "  ${GREEN}Docker Compose: $COMPOSE_VERSION${NC}"

# Check Python (optional - for seed scripts)
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version | grep -oP '\d+\.\d+\.\d+')
    echo -e "  ${GREEN}Python: $PYTHON_VERSION${NC}"
else
    echo -e "  ${YELLOW}Python 3 not found - seed scripts will not be available${NC}"
fi

echo ""

# ============================================================
# Copy .env.example to .env if not exists
# ============================================================
echo -e "${YELLOW}Configuring environment...${NC}"

ENV_FILE="$PROJECT_DIR/.env"
ENV_EXAMPLE="$PROJECT_DIR/.env.example"

if [ ! -f "$ENV_FILE" ]; then
    if [ -f "$ENV_EXAMPLE" ]; then
        cp "$ENV_EXAMPLE" "$ENV_FILE"
        echo -e "  ${GREEN}Created .env from .env.example${NC}"
        echo -e "  ${YELLOW}NOTE: Please review and update .env with your actual credentials before proceeding.${NC}"
    else
        echo -e "  ${YELLOW}WARNING: No .env.example found. Creating minimal .env...${NC}"
        cat > "$ENV_FILE" << 'ENVEOF'
# InHealth Chronic Care - Environment Configuration
# Generated by setup.sh - review and update all values

# Django
DJANGO_SECRET_KEY=change-me-in-production-use-50-char-random-string
DJANGO_DEBUG=True
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

# Database
POSTGRES_DB=inhealth_db
POSTGRES_USER=inhealth
POSTGRES_PASSWORD=change-me-strong-password
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
DATABASE_URL=postgresql://inhealth:change-me-strong-password@postgres:5432/inhealth_db

# Redis
REDIS_URL=redis://redis:6379/0

# Neo4j
NEO4J_URI=bolt://neo4j:7687
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=change-me-strong-password

# Qdrant
QDRANT_URL=http://qdrant:6333
QDRANT_API_KEY=

# OpenAI / LLM
OPENAI_API_KEY=your-openai-api-key-here
OPENAI_MODEL=gpt-4o
ANTHROPIC_API_KEY=your-anthropic-api-key-here

# Encryption
APP_ENCRYPTION_KEY=change-me-32-byte-encryption-key-here

# Monitoring
PAGERDUTY_CLINICAL_ROUTING_KEY=your-pagerduty-key
PAGERDUTY_INFRA_ROUTING_KEY=your-pagerduty-key
PAGERDUTY_AGENTS_ROUTING_KEY=your-pagerduty-key
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
SLACK_INFRA_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
SLACK_AGENTS_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
SLACK_CLINICAL_WEBHOOK_URL=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

# Grafana
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=change-me-strong-password

# JWT
JWT_SECRET_KEY=change-me-jwt-secret-key-here
JWT_EXPIRY_HOURS=24

# A2A Gateway
A2A_GATEWAY_PORT=3002
A2A_SECRET_KEY=change-me-a2a-secret

# MCP Server
MCP_SERVER_PORT=3003
ENVEOF
        echo -e "  ${GREEN}Created minimal .env file${NC}"
        echo -e "  ${RED}IMPORTANT: Update all 'change-me' values in .env before starting services!${NC}"
    fi
else
    echo -e "  ${GREEN}.env file already exists, skipping...${NC}"
fi

echo ""

# ============================================================
# Create required directories
# ============================================================
echo -e "${YELLOW}Creating required directories...${NC}"

DIRS=(
    "$PROJECT_DIR/monitoring/prometheus/rules"
    "$PROJECT_DIR/monitoring/alertmanager"
    "$PROJECT_DIR/monitoring/grafana/provisioning/datasources"
    "$PROJECT_DIR/monitoring/grafana/provisioning/dashboards"
    "$PROJECT_DIR/monitoring/grafana/dashboards"
    "$PROJECT_DIR/database/postgres"
    "$PROJECT_DIR/database/neo4j"
    "$PROJECT_DIR/database/redis"
    "$PROJECT_DIR/data/postgres"
    "$PROJECT_DIR/data/neo4j"
    "$PROJECT_DIR/data/redis"
    "$PROJECT_DIR/data/qdrant"
    "$PROJECT_DIR/data/grafana"
    "$PROJECT_DIR/data/prometheus"
    "$PROJECT_DIR/logs/django"
    "$PROJECT_DIR/logs/agents"
    "$PROJECT_DIR/logs/nginx"
    "$PROJECT_DIR/scripts"
    "$PROJECT_DIR/nginx/ssl"
    "$PROJECT_DIR/nginx/conf.d"
)

for DIR in "${DIRS[@]}"; do
    if [ ! -d "$DIR" ]; then
        mkdir -p "$DIR"
        echo -e "  ${GREEN}Created: $DIR${NC}"
    fi
done

# Set proper permissions for data directories
chmod -R 755 "$PROJECT_DIR/data" 2>/dev/null || true
chmod -R 777 "$PROJECT_DIR/data/grafana" 2>/dev/null || true
chmod -R 777 "$PROJECT_DIR/data/prometheus" 2>/dev/null || true

echo ""

# ============================================================
# Pull Docker images (optional)
# ============================================================
echo -e "${YELLOW}Pulling required Docker images...${NC}"
echo -e "  ${BLUE}This may take a few minutes on first run...${NC}"

if [ -f "$PROJECT_DIR/docker-compose.yml" ]; then
    cd "$PROJECT_DIR"
    $COMPOSE_CMD pull --quiet 2>&1 | tail -5 || echo -e "  ${YELLOW}Some images could not be pulled - will build locally${NC}"
    echo -e "  ${GREEN}Images ready${NC}"
else
    echo -e "  ${YELLOW}docker-compose.yml not found, skipping image pull${NC}"
fi

echo ""

# ============================================================
# Install Python dependencies (for seed scripts)
# ============================================================
if command -v python3 &> /dev/null && command -v pip3 &> /dev/null; then
    echo -e "${YELLOW}Installing Python dependencies for seed scripts...${NC}"
    REQUIREMENTS_FILE="$SCRIPT_DIR/requirements.txt"
    if [ -f "$REQUIREMENTS_FILE" ]; then
        pip3 install -r "$REQUIREMENTS_FILE" --quiet
        echo -e "  ${GREEN}Python dependencies installed${NC}"
    else
        # Install known script dependencies
        pip3 install neo4j qdrant-client openai python-dotenv requests --quiet 2>/dev/null || \
            echo -e "  ${YELLOW}Could not install Python dependencies - install manually if needed${NC}"
        echo -e "  ${GREEN}Python dependencies installed${NC}"
    fi
    echo ""
fi

# ============================================================
# Validate configuration
# ============================================================
echo -e "${YELLOW}Validating configuration...${NC}"

if [ -f "$ENV_FILE" ]; then
    # Check for any remaining 'change-me' values
    CHANGE_ME_COUNT=$(grep -c "change-me" "$ENV_FILE" 2>/dev/null || true)
    if [ "$CHANGE_ME_COUNT" -gt 0 ]; then
        echo -e "  ${YELLOW}WARNING: Found $CHANGE_ME_COUNT 'change-me' placeholder(s) in .env${NC}"
        echo -e "  ${YELLOW}Update these before deploying to production!${NC}"
    else
        echo -e "  ${GREEN}Environment configuration looks good${NC}"
    fi

    # Check for empty API keys
    if grep -q "OPENAI_API_KEY=$\|OPENAI_API_KEY=your" "$ENV_FILE"; then
        echo -e "  ${YELLOW}WARNING: OPENAI_API_KEY not configured - AI features will not work${NC}"
    fi
fi

echo ""

# ============================================================
# Success message with access URLs
# ============================================================
echo -e "${GREEN}"
echo "============================================================"
echo "  Setup Complete!"
echo "============================================================"
echo -e "${NC}"
echo "Next steps:"
echo "  1. Review and update .env with your credentials"
echo "  2. Start services:    ${BLUE}docker compose up -d${NC}"
echo "  3. Run migrations:    ${BLUE}docker compose exec django python manage.py migrate${NC}"
echo "  4. Create superuser:  ${BLUE}python3 scripts/create_superuser.py${NC}"
echo "  5. Seed Neo4j graph:  ${BLUE}python3 scripts/seed_graph.py${NC}"
echo "  6. Seed Qdrant:       ${BLUE}python3 scripts/seed_vectors.py${NC}"
echo "  7. Load guidelines:   ${BLUE}python3 scripts/load_guidelines.py${NC}"
echo ""
echo "Access URLs (after starting services):"
echo "  ${BLUE}Django API:        http://localhost:8000${NC}"
echo "  ${BLUE}Django Admin:      http://localhost:8000/admin${NC}"
echo "  ${BLUE}Agents API:        http://localhost:8001${NC}"
echo "  ${BLUE}MCP Server:        http://localhost:3003${NC}"
echo "  ${BLUE}A2A Gateway:       http://localhost:3002${NC}"
echo "  ${BLUE}Grafana:           http://localhost:3000${NC}"
echo "  ${BLUE}Prometheus:        http://localhost:9090${NC}"
echo "  ${BLUE}AlertManager:      http://localhost:9093${NC}"
echo "  ${BLUE}Neo4j Browser:     http://localhost:7474${NC}"
echo "  ${BLUE}Qdrant Dashboard:  http://localhost:6333/dashboard${NC}"
echo "  ${BLUE}Flower (Celery):   http://localhost:5555${NC}"
echo ""
echo -e "${GREEN}InHealth Chronic Care is ready to start!${NC}"
